require("prototypes.item.item-storage")
require("prototypes.item.item-groups")
require("prototypes.recipe.recipe-storage")
require("prototypes.entity.entity-storage")
require("prototypes.technology.technology-storage")